【問題1】行列積を手計算する

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

b_ndarray = [[(6),(-2+4+27),(-1-16-3)],[12,8-10+54,4+40-6],[-18,14+16-81,7-64+9]]
                
                =[[6,29,20],[12,52,38],[-18,-51,-48]]

【問題2】NumPyの関数による計算

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
t_ndarray = np.matmul(a_ndarray, b_ndarray)
print(t_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装

In [4]:
#行列の１行目を計算

a_array = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_array = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#print(a_array[0, 2]*b_array[2, 0])

array1_1 = 0
array1_2 = 0
array1_3 = 0
array2_1 = 0
array2_2 = 0
array2_3 = 0
array3_1 = 0
array3_2 = 0
array3_3 = 0

for i in range(3):
    array1_1 += a_array[0,i]*b_array[i,0]
for i in range(3):
    array1_2 += a_ndarray[0,i]*b_ndarray[i,1]
for i in range(3):
    array1_3 += a_ndarray[0,i]*b_ndarray[i,2]
for i in range(3):
    array2_1 += a_ndarray[1,i]*b_ndarray[i,0]
for i in range(3):
    array2_2 += a_ndarray[1,i]*b_ndarray[i,1]
for i in range(3):
    array2_3 += a_ndarray[1,i]*b_ndarray[i,2]
for i in range(3):
    array3_1 += a_ndarray[2,i]*b_ndarray[i,0]
for i in range(3):
    array3_2 += a_ndarray[2,i]*b_ndarray[i,1]
for i in range(3):
    array3_3 += a_ndarray[2,i]*b_ndarray[i,2]

t_array =  np.array([[array1_1, array1_2, array1_3], [array2_1, array2_2, array2_3], [array3_1, array3_2, array3_3]])
print(t_array)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題4】行列積を行う関数の作成

In [65]:
def nm_array(x_array,y_array):
    a_list = []
    if x_array.shape[1] == y_array.shape[0] and x_array.shape[0] == y_array.shape[1]:
        for l in range(y_array.shape[0]):
            for k in range(y_array.shape[0]):
                array1 = 0
                for i in range(x_array.shape[1]):
                    array1 += x_array[l,i]*y_array[i,k]
                a_list.append(array1)
            t1_array =  np.array(a_list)
        t1_array = np.array(t1_array)
        t2_array = t1_array.reshape(x_array.shape[1],y_array.shape[0])
    else:
        print("型が一致しないため計算できません")
    return t2_array
print(nm_array(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題5】計算が定義されない入力を判定する

In [66]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(nm_array(d_ndarray,e_ndarray))

型が一致しないため計算できません


UnboundLocalError: local variable 't2_array' referenced before assignment

【問題6】転置

In [68]:
print(np.matmul(d_ndarray, e_ndarray.T))
print(np.matmul(d_ndarray.T, e_ndarray))

[[ 46  -4]
 [-34  73]]
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
