# 【問題1】これまで利用してきたクラスの列挙

In [ ]:
"""サンプルコード
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
”””

In [ ]:
Pandas:DataFrame
matplotlib:ListedColormap
scikit-lear:KNeighborsClassifier

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
<br>
NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッド

In [1]:
"""
メソッド
accuracy_score()
DataFrame()
インスタンス変数
.metrics
.itertools
.shape
"""

SyntaxError: invalid syntax (<ipython-input-1-a97e9b0d5d27>, line 5)

# 【問題3】標準化クラスをスクラッチで作成

In [4]:
import pandas as pd
import numpy as np
import math

class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = sum(X)/len(X)
        self.var_ = sum([(self.mean_ - X_i) ** 2 for X_i in X])/len(X)
#         print(type(self.var_))
#         self.var_ = sum([(self.mean_ - X_i) ** 2 for X_i in X])/len(X)
#         for i in X:
#             var_amount += (mean - i) ** 2
#         self.var_ =　var_amount/len(X)
        self.std_ = np.sqrt(self.var_)
        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_)/self.std_
        
        pass
        return X_scaled
    
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
pd.DataFrame(X_std).describe()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


0             1          2             3
count  1.000000e+01  1.000000e+01  10.000000  1.000000e+01
mean   2.237099e-15  1.365574e-15   0.000000 -2.886580e-16
std    1.054093e+00  1.054093e+00   1.054093  1.054093e+00
min   -1.664222e+00 -1.407116e+00  -1.463850 -1.603567e+00
25%   -8.502002e-01 -7.207181e-01  -0.487950 -2.672612e-01
50%    1.447149e-01 -3.431991e-02  -0.487950 -2.672612e-01
75%    5.065022e-01  5.662785e-01   0.487950 -2.672612e-01
max    1.953651e+00  2.024875e+00   2.439750  2.405351e+00

# 【問題4】 四則演算を行うクラスの作成
<br>
上記ExampleClassに引き算、掛け算、割り算のメソッドを加える。
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出す。

In [19]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        if type(value2) == int: 
            self.value -= value2
        else:
            print("引数には数値を入力してください。")

    def subtract(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value *= value2
        
    def multiply(self, value2):
        """
        受け取った引数をかけてself.valueに戻す
        """
        self.value /= value2
        
    def divide(self, value2):
        """
        受け取った引数で割ってself.valueに戻す
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
d = [8,"a"]
example.add(d)
print("value : {}".format(example.value))
example.subtract(3)
print("value : {}".format(example.value))
example.multiply(3)
print("value : {}".format(example.value))
example.divide(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
引数には数値を入力してください。
value : 5
value : 15
value : 5.0
value : 8.0
